# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-16 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Postihnutie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazov', models.CharField(max_length=200)),
                ('druh', models.CharField(max_length=200)),
                ('uroven', models.CharField(max_length=20)),
                ('miera', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
