# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-16 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kompenz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postihnutie',
            name='miera',
        ),
        migrations.AddField(
            model_name='postihnutie',
            name='hornaHranica',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='postihnutie',
            name='spodnaHranica',
            field=models.IntegerField(default=0),
        ),
    ]
