# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-01 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kompenz', '0002_auto_20180717_0009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Osoba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meno', models.CharField(max_length=100)),
                ('priezvisko', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='postihnutie',
            name='kategoria',
            field=models.CharField(default='postih', max_length=200),
        ),
        migrations.AddField(
            model_name='osoba',
            name='postihnutie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kompenz.Postihnutie'),
        ),
    ]
