# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-17 01:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kompenz', '0003_auto_20180801_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kompenzacia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazov', models.CharField(max_length=100)),
                ('oblastKomp', models.CharField(max_length=200)),
                ('dochodkovyVek', models.BooleanField(default=False)),
                ('jednorazova', models.BooleanField()),
                ('maxPrispevok', models.IntegerField(default=100000)),
                ('prijem', models.IntegerField(default=350)),
            ],
        ),
        migrations.RemoveField(
            model_name='osoba',
            name='postihnutie',
        ),
        migrations.DeleteModel(
            name='Osoba',
        ),
    ]
