# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-08 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kompenz', '0004_auto_20180817_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postihnutie',
            name='uroven',
            field=models.CharField(choices=[('lah', 'ľahká'), ('str', 'stredná'), ('taz', 'ťažká')], max_length=3),
        ),
    ]
