# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-08 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kompenz', '0005_auto_20180909_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postihnutie',
            name='kategoria',
            field=models.CharField(choices=[('05', 'Nervový systém (poškodenie mozgu, miechy a periférnych nervov)'), ('12', 'Pohybový a podporný aparát')], max_length=2),
        ),
    ]
