# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-09 00:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kompenz', '0006_auto_20180909_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kompenzacia',
            name='oblastKomp',
            field=models.CharField(choices=[('a', 'a) mobility a orientácie'), ('b', 'b) komunikácie'), ('c', 'c) zvýšených výdavkov'), ('d', 'd) sebaobsluhy')], max_length=1),
        ),
    ]
